highlighter: rouge
permalink: none
kramdown:
  input: GFM
  hard_wrap: false
repository: rishabhjain2018/rishabhjain2018.github.io
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
# google_analytics: ''
title: Rishabh Jain
description: Rishabh is a Research Engineer at eBay. He works on building ML models & large scale ML systems. He leads an open source organization - CloudCV where he developed EvalAI, an open source platform for hosting AI challenges.
author: Rishabh Jain
twitter:
  username: rishabhjain2018
logo: images/contents/rishabh_jain.jpg
social:
  name: Rishabh Jain
  links:
    - https://twitter.com/rishabhjain2018
    - https://www.linkedin.com/in/rishabh-jain-2621a3b4
    - https://github.com/rishabhjain2018
