highlighter: rouge
permalink: none
kramdown:
  input: GFM
  hard_wrap: false
repository: rishabhjain2018/rishabhjain2018.github.io
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
# google_analytics: ''
title: Rishabh Jain
description: Computer Science MS student at Georgia Tech, advised by Dr. Dhruv Batra. He works at the intersection of Machine Learning & Software Engineering. He also leads an open source organization - CloudCV to build tools for reproducible AI research. 
author: Rishabh Jain
twitter:
  username: rishabhjain2018
logo: images/contents/rishabh_j.png
social:
  name: Rishabh Jain
  links:
    - https://twitter.com/rishabhjain2018
    - https://www.linkedin.com/in/rishabh-jain-2621a3b4
    - https://github.com/rishabhjain2018
